import getCurrentUser from '@/actions/getUser'
import Header from '@/components/Header'

const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function DashboardLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const currentUser = await getCurrentUser()

  return (
    <>
      <Header currentUser={currentUser} />
      {children}
    </>
  )
}
