import { getCurrentUser } from '@/server/services/getUser'
import Header from '@/components/DashboardNav'

const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default async function DashboardLayout({
  children
}: {
  children: React.ReactNode
}) {
  const currentUser = await getCurrentUser()

  return (
    <>
      <Header currentUser={currentUser} />
      {children}
    </>
  )
}
