import Header from '@/components/Header'
import '../styles/globals.css'
import { Inter } from 'next/font/google'
import getCurrentUser from '@/actions/getUser'
import { SessionProvider } from 'next-auth/react'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const currentUser = await getCurrentUser()

  return (
    <html lang="en">
      <body className={inter.className}>
        <Header currentUser={currentUser} />

        {children}
      </body>
    </html>
  )
}
