import QueryProvider from '@/providers/QueryProvider'
import '../styles/globals.css'
import { Inter } from 'next/font/google'
import { Toaster } from 'react-hot-toast'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'OPENLINK',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <QueryProvider>
        <body
          className={`relative bg-[#f3f3f1] h-screen w-full   ${inter.className}`}>
          <Toaster />

          <main className="max-w-5xl mx-auto h-full">{children}</main>
        </body>
      </QueryProvider>
    </html>
  )
}
