import Header from '@/components/Header'
import '../styles/globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={` bg-[#f3f3f1] h-screen w-full  ${inter.className}`}>
        <main className="relative mt-3  max-w-5xl mx-auto h-full">
          {children}
        </main>
      </body>
    </html>
  )
}
